[package]
authors = ["Ricardo Quesada <ricardoquesada@gmail.com>"]
description = "An interactive disassembler for the CPU 6502, focused mostly on Commodore 8-bit computers."
name = "regenerator2000"
version = "0.2.1"
edition = "2024"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/ricardoquesada/regenerator2000"
repository = "https://github.com/ricardoquesada/regenerator2000"
keywords = ["disassembler", "mos6502", "c64", "tui", "commodore"]
categories = ["development-tools::debugging"]
readme = "README.md"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ratatui-image = { version = "10.0.2", default-features = false, features = ["crossterm"] }
image = "0.25.9"
base64 = "0.22.1"
flate2 = "1.1.5"
directories = "6.0.0"
