[package]
name = "regenerator2000"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ratatui-image = "10.0.2"
image = "0.25.9"
base64 = "0.22.1"
flate2 = "1.1.5"
directories = "6.0.0"
