[package]
authors = ["Ricardo Quesada <ricardoquesada@gmail.com>"]
description = "An interactive disassembler for the CPU 6502, focused mostly on Commodore 8-bit computers."
name = "regenerator2000"
version = "0.6.3"
edition = "2024"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/ricardoquesada/regenerator2000"
repository = "https://github.com/ricardoquesada/regenerator2000"
keywords = ["disassembler", "mos6502", "c64", "tui", "commodore"]
categories = ["development-tools::debugging"]
readme = "README.md"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ratatui-image = { version = "9.0", default-features = false, features = ["crossterm"] }
image = "0.25.9"
base64 = "0.22.1"
flate2 = "1.1.8"
directories = "6.0.0"
tui-textarea = "0.7.0"
regex = "1.12.2"
log = "0.4.29"
simplelog = "0.12.2"

[build-dependencies]
anyhow = "1.0"
vergen = "9.1.0"
vergen-gitcl = "9.1.0"
