site_name: Regenerator 2000
site_author: Ricardo Quesada
site_description: >-
  Documentation for Regenerator 2000, a modern interactive disassembler
  for the CPU 6502, focused mostly on Commodore 8-bit computers.
  Features a TUI with modern features like x-ref, undo/redo, arrows,
  keyboard-driven and more!

site_url: http://regenerator2000.readthedocs.io/
repo_url: https://github.com/ricardoquesada/regenerator2000
repo_name: ricardoquesada/regenerator2000

copyright: Copyright &copy; 2026 Ricardo Quesada & contributors

edit_uri: edit/main/docs/

watch:
  - README.md
  - CHANGELOG.md

theme:
  name: material
  logo: regenerator2000_logo_noname.png
  favicon: regenerator2000_logo_favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.top
    - navigation.tracking

nav:
  - Home: index.md
  - Getting Started:
      - Installation & Usage: install.md
      - Views: views.md
      - Blocks: blocks.md
  - User Reference:
      - Keyboard Shortcuts: keyboard_shortcuts.md
      - Settings: settings.md
      - Assemblers: assemblers.md
      - FAQ: faq.md
  - Development & Internals:
      - Architecture: architecture.md
      - Graphics Module: graphics_module.md
      - Requirements: requirements.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - admonition

plugins:
  - include-markdown
  - search

extra:
  analytics:
    provider: google
    property: G-K9JX0F7781
